### PR TITLE
last hash

### PR DESCRIPTION
**Pull request by trkohler**

### CODE REVIEW

**Comment by dmvict** [comment]
We need to find last block hash, not mercle hash. 

Please, fix method.

**Comment by trkohler** [comment]
i'm not sure i'm aware of difference 
may i ask to explain please?

**Comment by trkohler** [comment]
ok probably i got it

you meant hash of last block body?

**Comment by dmvict** [comment]
> ok probably i got it
> 
> you meant hash of last block body?

Now, I'm not sure about body, or block itself. It should have the same hash.

**Comment by trkohler** [comment]
maybe this hash will be ok?

**Comment by dmvict** [comment]
Thanks

**Pull request merged**
